- README.md
- prometheus_client/__init__.py
- setup.py
- tests/test_client.py
set_to_current_time doesn't take an argument.
> Use snake case for method names.

- prometheus_client/__init__.py
- tests/test_client.py
Make __all__ work with unicode_literals
Fixes #18
> Coerce label values to strings.

- README.md
- prometheus_client/__init__.py
- tests/test_client.py
This is useful for code that knows some of the labels in different places.
An example use case is a helper I'm trying to write that would work as such:
c = Counter('http_exceptions_total', 'help', ['method', 'exception_type'])
def handle_request(request):
with count_exceptions_by_type(c, {'method': request.method}):
do_something(request)
This helper only knows about the exception_type label and only passes
the other labels through.
> Add the ability to specify labels as a dict of labelname->labelvalue.

- prometheus_client/exposition.py
- tests/graphite_bridge.py
- tests/test_client.py
@brian-brazil: This bundles together a few small fixes for the tests. Please let me know if you would prefer them as separate pull requests.
- First of all, `test_client.py` contained two tests with the same name (`test_pushadd_with_groupingkey`), so I renamed the second one to the more appropriate `test_delete_with_groupingkey`.
- I also noticed a race condition in the tests, where the assertions that check the received request could be run just before the requests are stored. I fixed this by calling `send_response` after the request is stored, instead of before.
- I then looked at issue #46. It seems there are some small differences in either the HTTP server or client between Python 2.7 and 3.4, which means a call to `end_headers` is required in the HTTP handler for Python 3.4.
- …
> Several small test fixes

- prometheus_client/bridge/graphite.py
- tests/graphite_bridge.py
1. An optional `prefix` parameter in `bridge.graphite.GraphiteBridge.push()`.
2. `prefix` is prepended to metrics name before sending to graphite server.
3. Unit test.
Issue #49
> Support for namespace in graphite bridge

- prometheus_client/process_collector.py
Good Afternoon!
This  change is to start standardizing the help text between client libraries.
Equivalent in [client_golang](https://github.com/prometheus/client_golang/blob/fcd2986466589bcf7a411ec3b52d85a8df9dcc8b/prometheus/process_collector.go#L69)
Related to: https://github.com/prometheus/client_golang/issues/171
Take care,
Nicholas
> Update help text to match client_golang

- AUTHORS.md
- README.md
- prometheus_client/core.py
In an attempt to bolster the docstrings in the core.py file,
some of the README docs were copied into the core.py.
@brian-brazil
> Copy some README docs into core.py docstrings 

- README.md
- prometheus_client/twisted/__init__.py
- prometheus_client/twisted/_exposition.py
- setup.py
- tests/test_twisted.py
I'm not sure if this belongs as part of the client, or should be an external package that depends on this.
> Add a twisted resource for exposing metrics via twisted.web.

- prometheus_client/core.py
classes are relatively expensive to create, and particularly disadvantageous on PyPy
A benchmark could be created if this was useful
> Unnest the Timer class

- prometheus_client/exposition.py
This is just a quick fix to let the bulit-in WSGI server serve a non-default registry
> Adds support for the WSGI server to read from a different registry

- .travis.yml
- setup.py
- tests/test_exposition.py
- tests/test_parser.py
- tests/test_twisted.py
- tox.ini
As discussed in #86, this adds Python 2.6 support for the tests and CI.
Since 2.6’s stdlib doesn’t support test skipping, we have to resort to using the back port unittest2.
There are a few ways to make it less ugly:
- use unittest2 unconditionally everywhere.  has also the benefit of a consistent test environment.
- do the dance once in a helper module (say `tests/utils.py`) and then just import unittest from there.
- use pytest for skipping
> Make tests pass on Python 2.6

- .coveragerc
- NOTICE
- prometheus_client/core.py
- prometheus_client/decorator.py
- tests/test_core.py
As discussed in #77, this PR bundles (to avoid dependencies) the decorator.py module and uses it to fix the behavior of prometheus_client's decorators.
The efficacy can be verified by using example view from the README and then doing a:
```pycon
>>> from inspect import getargspec
>>> getargspec(process_request)
ArgSpec(args=['t'], varargs=None, keywords=None, defaults=None)
```
Without this patch, you get:
```pycon
ArgSpec(args=[], varargs='args', keywords='kwargs', defaults=None)
```
instead.
Let me now what you think.
Also pinging @micheles out of courtesy and to ensure he doesn’t feel we violate his copyright.
> Bundle decorator.py and fix decorators

- prometheus_client/exposition.py
We are using a push gateway behind an https reverse proxy. `push_gateway` and related functions previously assumed http and prepended the scheme no matter the circumstances. This patch checks to see if the user has specified a scheme. And, if not, it defaults to http.
I ran the tests on both python 2.7.10 and 3.5.2 and they pass just fine. So we've got backward-compatibility. But I didn't see a very obvious way to get an https server into the test.
Thanks @brian-brazil
> Add optional scheme support for push gateway urls

- prometheus_client/bridge/graphite.py
- prometheus_client/core.py
- tests/test_graphite_bridge.py
On Python 3, this uses `time.perf_counter` on all platforms.
On Python 2, it will use `time.clock` on Windows and `time.time` everywhere else
> Use timeit.default_timer instead of time.time

- .travis.yml
- README.md
- prometheus_client/core.py
- prometheus_client/multiprocess.py
- tests/test_multiprocess.py
This works by having a shelve per process that are continously updated
with metrics, and a collector that reads from them.
Histogram buckets need accumulation and special handling for _count,
and for gauges we need to offer a number of options.
Fixes #30
> Add multi-process support

- prometheus_client/core.py
set_to_current_time is expected to set the value to a realistic time.
Performance counters are monotonic but don't say anything about the actual
time.
> Use realistic timer for Gauge.set_to_current_time

- README.md
- prometheus_client/core.py
- prometheus_client/exposition.py
- tests/test_core.py
This is the first pass on limiting what's returned over http exposition via a url parameter. We'll likely need to support POST also in future to get around URL length limits.
@juliusv @fabxc @beorn7 @SuperQ 
Fixes #97
> Add describe and limiting of http expostion

- prometheus_client/exposition.py
@brian-brazil 
This change allows each HTTP request to be served by a separate thread (I think!).
This came about because of a network issue, which was causing one Prometheus to keep a connection open - causing all other Proms to fail the exporter as they couldn't get a connection.
This is also consistent with the Go exporter behavior.
Cheers,
James
> Changes to allow each HTTP request to be a seperate thread

- prometheus_client/core.py
- tests/test_core.py
Docs demonstrate initializing a metric's labels with a list, but `labelnames` is internally represented as a tuple. If `labelnames` is truthy, it gets cast to a tuple (and a reasonable error is thrown if it can't be cast), but `_MetricWrapper` simply forwards `labelnames` as-is if it is falsy.
This is normally not a problem, but when initializing a histogram with an empty labels list:
```
from prometheus_client import Histogram
Histogram('h', 'help', [])
```
this error occurs:
```
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/usr/local/lib/python2.7/dist-packages/prometheus_client/core.py", line 539, in init
collector = cls(name, labelnames, (), **kwargs)
File "/usr/local/lib/python2.7/dist-packages/prometheus_client/core.py", line 835, in __init__ …
```
> Fix error when initializing histogram with empty labels list

- README.md
We need to use the recently added Gunicorn `child_exited` callback in order to
correctly clean up after a segfaulted or OOM-killed worker (for details, see
https://github.com/benoitc/gunicorn/pull/1394 and #115).
The try catch is necessary to guard against unexpected race conditions and
errors in the cleanup logic. I have seen this twice, crippling the master
process in a cascading failure scenario.
> Provide robust Gunicorn config in multiprocess docs

- prometheus_client/core.py
- tests/test_core.py
> Expose original metric classes via __wrapped__ attribute

- README.md
- prometheus_client/__init__.py
- prometheus_client/platform_collector.py
- tests/test_platform_collector.py
In the same vein as https://github.com/prometheus/client_java/commit/bdc6f2507a81029c1aec6cd8b5276661bb6c7ee1 and https://github.com/siimon/prom-client/commit/ee561e28e14a62b0ef069f525174ee9a3b66d4d7, this PR adds Python version and some other metadata as labels on a small set of metrics.
This has turned out to be very useful for creating common dashboards across implementation languages, allowing the dashboard to extract metadata from the metrics exposed.
Python, machine and system information is collected once at startup, and
exposed as labels on a metric with value 1.
> Add PlatformCollector to collect information about the platform

- prometheus_client/__init__.py
Previously the code included:
from __future__ import unicode_literals
But with that gone in the current version, it makes no sense to mess with the contents of `__all__` at all.
> Remove hack to encode __all__ as ascii

- README.md
- prometheus_client/core.py
- tests/test_multiprocess.py
This puts us at ~2000ns for an operation,
which is ~300ns than previously but still slightly
better than we were before we switched to a single lock.
This is twice as slow as without multiproc mode.
> Reset multiproc values when the pid changes.

- .travis.yml
- setup.py
- tox.ini
Add py36 to the Travis CI config, and `setup.py` classifiers.
Also tweak local tox config, install twisted for 3.6 but make `noptionals` variant use 2.7 and 3.5 only.
> Test and support Python 3.6

- prometheus_client/core.py
- tests/test_core.py
On Python 3 the labels of the `python_info` metric is a reference to the `dict_keys` of the data object used to create it. This PR ensures all labelnames in MetricFamilies it are a static tuple instead.
This PR is motivated by some broken tests in https://github.com/korfuri/django-prometheus with recent versions of prometheus-client: https://github.com/korfuri/django-prometheus/pull/46#issuecomment-320453360
Although the docs do not say Metrics should be serializable this change seems more in keeping with the intention that labels should be owned by the Metric and not a reference to an external object.
> Convert MetricFamily labels -> list

- prometheus_client/exposition.py
Logging using `start_http_server()` and `start_wsgi_server()` is now consistent.
Also simplifies and documents the server creation logic without otherwise changing behaviour.
> Make WSGI metrics server not log requests

- prometheus_client/multiprocess.py
- tests/test_multiprocess.py
On head it fails with:
```python
ERROR in app: Exception on /metrics [GET]
AttributeError: 'NoneType' object has no attribute 'endswith'
```
With this change:
```python
File "build/bdist.linux-x86_64/egg/prometheus_client/multiprocess.py", line 16, in __init__
raise ValueError('env prometheus_multiproc_dir is not set or not accessible')
ValueError: env prometheus_multiproc_dir is not set or not accessible
```
> helpful error message when multiprocessing dir env is unset

- prometheus_client/exposition.py
If python version is 2.6 or older, check if scheme is one of “http" or "https".
> Fix issue #208: parse the correct scheme of URL in Python26

- tox.ini
for py26: fix dependencies: `pytest`, `py`
> py26 has fixed dependencies

- prometheus_client/core.py
- tests/test_core.py
I thought this one was missing from prometheus_client.core, so that's why I propose to add it. But their may be a reason why it wasn't added in the first place.
> Add UntypedMetricFamily to prometheus_client.core

- prometheus_client/exposition.py
- prometheus_client/multiprocess.py
- tests/test_exposition.py
Add `registry` parameter to start_http_server, so you can serve data
from a custom registry.
Added:
- the optional named parameter `registry` to `start_http_server`
- create a  MetricHandler tied to the passed `registry` via MetricHandler.factory 
Create a new or a multiprocess registry
Pass `registry=myregistry` to start_http_server.
```
from prometheus_client import multiprocess, start_http_server
from prometheus_client import Counter
...
myregistry = CollectorRegistry()
start_http_server(8000, registry=myregistry)
start_http_server(8001) 
...
```
> Fix: #222. Support custom registry for MetricsHandler.

- prometheus_client/decorator.py
- prometheus_client/exposition.py
sys.version_info is a parsed tuple of numbers, so not vulnerable to incorrect string version comparison (e.g. '10' < '3') or parse errors on sys.version.
Discovered because prometheus-client cannot be imported on development versions of Python which have version strings like `3.7.0a0`.
> check Python version with sys.version_info

- prometheus_client/exposition.py
- tests/test_exposition.py
Explicitly passing `None` will still trigger the no timeout behaviour of the underlying Python http/socket modules.
This is motived by hitting an odd case in a k8s cluster job where some job pods were hung for 2 hours in the finally-post-metrics step after some cluster unhappiness that had since been resolved. However, I couldn't later reproduce the behaviour locally, as my machine at least does timeout the socket after a reasonable window regardless.
Even so, was worth adapting our application code to set a timeout, and having a sensible default in the client library here also seems reasonable.
> Set default timeout of pushgateway actions to 30s

- .travis.yml
From the linked issue, it's now possible with travis to explictly
select a newer pypy version to use, so pick the latest 5.10.0 one.
> Remove travis pypy version hack and use latest

- tox.ini
Add ignore rules for all current lint failures, they can be tackled
in follow up branches along with enabling each rule.
> Add tox env for running flake8 lint

- prometheus_client/exposition.py
Ensure that if a WSGI server does not provide the QUERY_STRING in the
environ, that we don't throw an exception and cause a 500 to be returned
to the scraping client.
@brian-brazil
> PEP333 does not require QUERY_STRING to be present.

- prometheus_client/multiprocess.py
Hi!
I will try to improve multiprocess metrics collections by a series of pull requests.
This one fixes unnecessary metric creation in loop.
The more correct way to use `dict.setdefault` is `result = dict.setdefault(key, value)`. In our case:
```
metric = metrics.setdefault(metric_name, core.Metric(...))
```
instead of
```
metrics.setdefault(metric_name, core.Metric(...))
metric = metrics[metric_name]
```
But the problem is that `core.Metric(...)` will be executed each time when **setdefault** method calls whether needed or not.
> Reduce unnecessary metric creation in loop

- prometheus_client/multiprocess.py
Hi!
This is the next performance pull request. This change is about using `collections.defaultdict` for counting samples. It works much faster than `setdefault` method:
```
In [1]: from collections import defaultdict
In [2]: d={}
In [3]: %timeit d.setdefault('key', 0.0);d['key']+=1
197 ns ± 7.5 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
In [4]: d
Out[4]: {'key': 8111111.0}
In [5]: d=defaultdict(float)
In [6]: %timeit d['key']+=1
80.9 ns ± 0.841 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
In [7]: d
Out[7]: defaultdict(float, {'key': 81111111.0})
```
> Use `collections.defaultdict` to speed up metrics aggregation

- prometheus_client/core.py
- prometheus_client/multiprocess.py
In multiprocess mode, when reading metrics from files, there is no need to read all values in constructor, because `read_all_values` method called explicitly in multiprocess collector.
> Prevent double reading all values when collect multiprocess metrics

- prometheus_client/core.py
Notes for struct usage optimizations: https://docs.python.org/2/library/struct.html#classes
Regarding string formatting:
```
In [1]: %timeit '%s' % 1
14.7 ns ± 0.325 ns per loop (mean ± std. dev. of 7 runs, 100000000 loops each)
In [2]: %timeit '{0}'.format(1)
134 ns ± 2.93 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
```
> Use precompiled struct methods for pack, unpack data

- tests/test_core.py
- tests/test_exposition.py
- tests/test_parser.py
- tox.ini
Resolves F841.
Also improves several tests to assert on relevant behaviours.
> Fix lint related to assigned but unused variables

- prometheus_client/core.py
- prometheus_client/parser.py
- tests/test_parser.py
Hi,
As we extensively use this library for parsing prometheus text format, we have observed that for big payloads (like https://github.com/kubernetes/kube-state-metrics for a big cluster) that can contains 400k+ lines the text parsing can be quite slow. (up to 27secs)
We tried to optimize the parser by dropping the state machine and leveraging native python functions such as `index` or `find` and it gives us an average of x5 performances.
Here are some benchmark using `timeit`:
```
call (x100000): _parse_sample('simple_metric 1.513767429e+09')
previous implementation: 1.10845804214
new implementation: 0.277444839478
improvement: x3.99523755508
call (x100000): _parse_sample('kube_service_labels{label_app="kube-state-metrics",label_chart="kube-state-metrics-0.5.0",label_heritage="Tiller",lab …
```
> Text parser optimization (~4.5x perf)

- prometheus_client/core.py
- tests/test_core.py
- tox.ini
Fixes #287.
Creates new timer object on each invocation - this solves both reentrancy and thread safety (added a test for reentrancy).
It's about 5% slower than the previous version with TLS, but in fact it's only 0.12us (micro) difference per function call. Assuming that actual functions will do other things besides updating metrics, I think it's quite negligible.
Here are the detailed performance test results:
```
Timing manual `observe'
10000000 loops in 14.906 seconds
1.491us per iteration
670.875k iterations per second
Timing ThreadLocalTimer
10000000 loops in 23.368 seconds
2.337us per iteration
427.944k iterations per second
Timing ObjectTimer
10000000 loops in 24.539 seconds
2.454us per iteration
407.510k iterations per second
```
And the actual performance test code:
```python …
```
> Thread safety done right

- README.md
I'm working on a flask application that needs to expose metrics to prometheus. It was not very clear how that could be done without reading the code. This PR updates the README with a simple example of doing so. Hopefully it saves someone some time of trying to figure that out.
@brian-brazil
> Example on how to expose metrics in a flask app

- README.md
- prometheus_client/__init__.py
- prometheus_client/bridge/graphite.py
- prometheus_client/core.py
- prometheus_client/exposition.py
- prometheus_client/multiprocess.py
- prometheus_client/openmetrics/exposition.py
- prometheus_client/openmetrics/parser.py
- prometheus_client/parser.py
- prometheus_client/twisted/_exposition.py
- setup.py
- tests/openmetrics/test_exposition.py
- tests/openmetrics/test_parser.py
- tests/test_core.py
- tests/test_exposition.py
- tests/test_graphite_bridge.py
- tests/test_multiprocess.py
- tests/test_parser.py
- tests/test_platform_collector.py
This should handle all valid inputs, but does not yet reject all invalid inputs.
> Initial work on OpenMetrics

- prometheus_client/core.py
- prometheus_client/multiprocess.py
- tests/test_multiprocess.py
Factors out a merge() method from the previous collect() method, which
is parameterized, and thus can be used for arbitrary merging of samples.
For motivation, see discussion in issue #275 around merging dead worker's
data into a single mmaped file.
This basically allows us to parameterize the files to be merged, and
also whether to accumulate histograms or not. Accumulation is on by
default, as that is what the prometheus format expects. But it can now
be disabled, which allows merged values to be correctly written back to
an mmaped file. For the same reason, the order of labels is preserved
via OrderedDict.
> Refactor MultiProcessCollector.collect() to allow for arbitrary merging.

- prometheus_client/__init__.py
- prometheus_client/gc_collector.py
- tests/test_gc_collector.py
We've found this useful in monitoring pythons Garbage Collection. If you are
interested in including this:
- Should the name default to python_gc perhaps?
- Are you happy for these all to be histograms?
- If so, how would you prefer the buckets to be set up (presumably defaulted and
pass in to the constructor?)
- I'm not actually sure if having uncollected as a histogram is of much use. Uncollected
should be monitored, but histogram is probably overkill.
- I'll fill out the tests?
> Add detailed Garbage Collection statistics.

- prometheus_client/core.py
@brian-brazil 
Using `struct.pack_into` can create atomicity problems when writing on CPython, setting the bytes to 0 before writing the value.
When having a lot of writes, some reads would return 0 instead of the real value. This line in CPython is suspected: https://github.com/python/cpython/blob/2.7/Modules/_struct.c#L1563
You can reproduce the issue by having two scripts running in two different processes but using the same file, one writing an always incrementing counter and the other reading it. Sometimes, the reader script will read 0 instead of the real value. We encountered this in production by running a Django web service behind gunicorn.
Example writer script:
```python
#!/usr/bin/python
import time
from prometheus_client.core import _MmapedDict
f = _MmapedDict('mf.db')
start …
```
> Multiprocess mode: using direct assignment for writing into mmap

- prometheus_client/core.py
- prometheus_client/exposition.py
- prometheus_client/openmetrics/exposition.py
- prometheus_client/openmetrics/parser.py
- tests/openmetrics/test_exposition.py
- tests/openmetrics/test_parser.py
- tests/test_core.py
- tests/test_exposition.py
Allow gsum, gcount, and created to be sanely returned in Prometheus
format.
Extend openmetrics parser unittests to cover Info and StateSet.
@SuperQ
> Add gsum/gcount to GaugeHistogram.

- .gitignore
- prometheus_client/gc_collector.py
To avoid deadlocks (#322), disable the GC collector in multiprocess mode.
> Disable GCCollector in multiprocess mode

- prometheus_client/bridge/graphite.py
- prometheus_client/core.py
- prometheus_client/decorator.py
- prometheus_client/exposition.py
- prometheus_client/gc_collector.py
- prometheus_client/multiprocess.py
- prometheus_client/openmetrics/exposition.py
- prometheus_client/openmetrics/parser.py
- prometheus_client/parser.py
- prometheus_client/process_collector.py
- prometheus_client/twisted/_exposition.py
- setup.cfg
- tests/openmetrics/test_exposition.py
- tests/openmetrics/test_parser.py
- tests/test_core.py
- tests/test_exposition.py
- tests/test_gc_collector.py
- tests/test_graphite_bridge.py
- tests/test_multiprocess.py
- tests/test_parser.py
- tests/test_process_collector.py
- tests/test_twisted.py
This PR fixes some wonky indentation (there were occasions of non-4-divisible indentation 😱 ) both mechanically (`autopep8`) and by hand where manually rewrapping code lead to more readable statements. (That, too, could be automated with something like `black`.)
In addition, there were some duplicate imports, which were cleaned up with `isort`. A `setup.cfg` file was added to configure the multi-line import style to match the one most used in the project.
> Code style fixups

- prometheus_client/core.py
- prometheus_client/exposition.py
- prometheus_client/multiprocess.py
- setup.cfg
- tests/test_core.py
- tests/test_exposition.py
- tests/test_multiprocess.py
- tests/test_parser.py
- tox.ini
With #325 by @akx has landed, the flake8 rules on import style lint can be enabled.
Combined the isort `setup.cfg` into `tox.ini` and added a couple of extra config options so it passes the default flake8 rules.
As it wasn't very obvious that there was existing lint tooling #326 updates `CONTRIBUTING.md` to point it out.
> Enable flake8 import lint checking

- CONTRIBUTING.md
Mention the DCO signing requirement and link wiki page with details.
Add section on testing requirements and tools.
Add section on code style and lint details.
> Update CONTRIBUTING.md for DCO, test, and lint

- prometheus_client/core.py
- tests/test_multiprocess.py
Without this, when forking, children can initialise metrics to the
cached master pid file. This is racy, and can corrupt the master's
mmaped file, breaking all subsequent collections.
> In multiprocess mode, ensure that metrics initialise to the correct file

- prometheus_client/core.py
- tests/test_multiprocess.py
This is a follow on fix for the initialisation corruption fixed in #328.
When corruption of the master's mmaped file occured, it ended up reading the corrupted data as an large integer. It would then feed this into *struct.unpack_from* as the length to read, which would rightly raise an exception.
However, it also somehow caused a much bigger problem. After this had occurred, Gunicorn would for some unknown reason fail to successfully launch new workers, and thus exit. We saw this pattern of corruption and subsequent gunicorn death happen consistently over multiple machines and services. 
The issue was transient, and we didn't get coredumps, but the suspicion is that trying to read a large chunk of memory somehow broke gunicorn. 
So this change adds a reasonable bounds check on read …
> Limit memory reads for mmaped files

- prometheus_client/__init__.py
- prometheus_client/twisted/_exposition.py
The contribution guide says that new code should be flake8 compliant, so this fixes ordering in a couple of import statements which were previously causing that test to fail. :)
I didn't add `- env: TOXENV=flake8` to the `travis.yml` file, though maybe that wouldn't be a terrible idea.
@brian-brazil
> flake8 compliance

- prometheus_client/exposition.py
- tests/test_exposition.py
@brian-brazil 
Changes MetricsHandler.factory from a staticmethod to a classmethod to be able to determine the correct subclass to return. This way if a user wants to extend the behavior of their MetricsHandler, they don't have to reimplement the factory() method.
> Permit subclassing of MetricsHandler

- prometheus_client/gc_collector.py
It looks like the Python GC engine can call the GC callback
while it's still being called (likely if the callback does significant
enough work), which may, if you're unlucky enough, lead into a stack
overflow Python is unable to recover from.
This patch should fix it, though no empirical tests have been made.
Refs this issue comment: https://github.com/prometheus/client_python/issues/322#issuecomment-438021132
> Avoid re-entrant calls to GC collector's callback

- prometheus_client/openmetrics/parser.py
- prometheus_client/utils.py
- tests/openmetrics/test_parser.py
- tests/test_parser.py
> Float histograms

- prometheus_client/exposition.py
The leak is caused by the fact that in Python 3.7, the default behavior
of the `ThreadingMixin` is to use no daemon threads, but to request to
block on threads on close. Because of that, it collects references to
all created threads, creating the "leak":
https://github.com/python/cpython/blob/v3.7.0/Lib/socketserver.py#L661
* Python 3.7: `block_on_close` is `True`: https://github.com/python/cpython/blob/v3.7.0/Lib/socketserver.py#L635
* Python 3.6: `_block_on_close` is `False`: https://github.com/python/cpython/blob/v3.6.7/Lib/socketserver.py#L639
* Python 2.7: There is no `block_on_close`, thus no logic for collecting
references: https://github.com/python/cpython/blob/v2.7.15/Lib/SocketServer.py#L582
Fix by setting `daemon_threads` to `True`, which in our case should be a
reasonable …
> Fix thread leak in Python 3.7 #340

- prometheus_client/samples.py
- prometheus_client/utils.py
- tests/openmetrics/test_parser.py
This should restore compatibility with Python 2.6, current version fails with:
```
Traceback (most recent call last):
...
File "/usr/lib/python2.6/site-packages/prometheus_client-0.5.0-py2.6.egg/prometheus_client/exposition.py", line 194, in write_to_textfile
f.write(generate_latest(registry))
File "/usr/lib/python2.6/site-packages/prometheus_client-0.5.0-py2.6.egg/prometheus_client/exposition.py", line 119, in generate_latest
output.append(sample_line(s))
File "/usr/lib/python2.6/site-packages/prometheus_client-0.5.0-py2.6.egg/prometheus_client/exposition.py", line 86, in sample_line
s.name, labelstr, floatToGoString(s.value), timestamp)
File "/usr/lib/python2.6/site-packages/prometheus_client-0.5.0-py2.6.egg/prometheus_client/utils.py", line 21, in floatToGoString
mantissa = …
```
> Make the format strings compatible with Python 2.6

- prometheus_client/decorator.py
This seemed to be trivial one so I didn't open an issue. This fixes a `SyntaxWarning` introduced on CPython master that will be released as 3.8. It's already a `DeprecationWarning` on Python 3.6. The escape sequence needs to be present inside a raw string to fix the warning.
```
prometheus_client/decorator.py:82
/home/karthi/client_python/prometheus_client/decorator.py:82: SyntaxWarning: invalid escape sequence \s
DEF = re.compile('\s*def\s*([_\w][_\w\d]*)\s*\(')
```
Thanks for the library :)
> Fix SyntaxWarning due to unescaped sequence

- prometheus_client/gc_collector.py
- tests/test_gc_collector.py
Hello!
Regading https://github.com/prometheus/client_python/issues/363
We have the same problem with asyncio using (aiohttp, single process, single thread)
As we cannot predict when `gc.collect()` will be executed (with `gc.enable`), it is not possible to use something that has locks inside the `gc.collect` callbacks. So, YES, we neet to reconsidered how the GC collector works.
One way it is remove GC Collector  :sunglasses:  . 
Another way in this PR - Collect metrics in simle structures witout locks and represent it in 'collect' method.
Therd way is to use `gc.stats` (since python 3.4) with Gauge (`GaugeMetricFamily`) metrics at `collect`.
Or as @megabotan said, just remove lock in `get` methof of `MutexValue`
> Deadlock on gcCollector

- .travis.yml
- prometheus_client/gc_collector.py
- tests/test_gc_collector.py
- tox.ini
We use `gc.get_stats` to provide metrics at `gcColector` . Pypy gc have the same method but they are very different. (https://github.com/prometheus/client_python/issues/378 http://doc.pypy.org/en/latest/gc_info.html#gc-get-stats)
I think it is better just to not provide gc metrics with pypy.
> Disable gcCollector for pypy

- README.md
Maybe the link to `instrumentation best practices` should be
https://prometheus.io/docs/practices/instrumentation/#counter-vs-gauge-summary-vs-histogram
> Fix instrumentation link in README

- prometheus_client/openmetrics/parser.py
- tests/openmetrics/test_parser.py
Per recent discussions.
@SuperQ
> Change exemplar length limit to be only for label names+values

- prometheus_client/openmetrics/parser.py
- tests/openmetrics/test_parser.py
This PR optimizes the openmetrics parser using the logic introduced in https://github.com/prometheus/client_python/pull/282 to optimize the prometheus parser.
Here are some benchmark using `timeit`:
```
call (x100000): _parse_sample('simple_metric 1.513767429e+09')
Simple example with prometheus parser: 0.2489180564880371
Simple example with openmetrics parser: 1.1144659519195557
Simple example with the optimized openmetrics parser: 0.5948491096496582
call (x100000): _parse_sample('kube_service_labels{label_app="kube-state-metrics",label_chart="kube-state-metrics-0.5.0",label_heritage="Tiller",label_release="ungaged-panther",namespace="default",service="ungaged-panther-kube-state-metrics"} 1')
KSM metric example with prometheus parser: 1.6796550750732422
KSM metric example openmetrics …
```
> optimize openmetrics text parsing (~4x perf)

- .travis.yml
- setup.py
- tests/test_gc_collector.py
- tox.ini
Signed-off-by: Stanislav Kudriashev <stas.kudriashev@gmail.com>
> Add python3.7 support

- prometheus_client/mmap_dict.py
- prometheus_client/multiprocess.py
Hey there!
We at @valohai are still (#367, #368) bumping into situations where a long-lived multiproc (uWSGI) app's metric exposition steadily gets slower and slower, until it starts clogging up all workers and bumping into Prometheus's deadlines, and things break in a decidedly ungood way.
I figured I could take a little look at what exactly is taking time there, and I'm delighted to say I managed to eke out a roughly 5.8-fold speed increase in my test case (2857 files in the multiproc dir, totaling 2.8 GiB).
By far the largest boost here came from actually not using `mmap()` at all (f0319fa) when we're only reading the file; instead, simply reading the file fully into memory and parsing things from the memory buffer is much, much faster. Given each file (in my case anyway) is about 1 …
> Multiprocess exposition speed boost

- prometheus_client/multiprocess.py
- tests/test_multiprocess.py
> multiprocess: don't crash on missing gauge_live/sum files

- prometheus_client/metrics.py
In Python2, the `MethodType` constructor requires the obj‘s class to be passed. Compact code is copied from `six` https://github.com/benjaminp/six/blob/8da94b8a153ceb0d6417d76729ba75e80eaa75c1/six.py#L545-L556
> Compact types.MethodType between 2 and 3

- prometheus_client/openmetrics/parser.py
- tests/openmetrics/test_parser.py
> Add support for exemplars on counters.

- prometheus_client/exposition.py
- tests/test_exposition.py
Signed-off-by: Brian Brazil <brian.brazil@robustperception.io>
@beorn7
> Support slashes in pgw grouping keys.

- prometheus_client/process_collector.py
I'm trying to use this on Google App Engine standard (python 2.7) just to export some custom metrics.  This line throws an OSError.
I also had some trouble with the multiprocess mmap stuff.  Just dropping something into sys.modules['prometheus_client.mmap_dict'] seems to work well enough to solve that one, though.
> except OSError

- prometheus_client/openmetrics/parser.py
- tests/openmetrics/test_parser.py
> Check for duplicate label names, add missing checks on new code path.

- prometheus_client/metrics.py
- tests/test_core.py
This is for issue https://github.com/prometheus/client_python/issues/454
> Add observability check to counters

- prometheus_client/exposition.py
- prometheus_client/gc_collector.py
- prometheus_client/multiprocess.py
- prometheus_client/parser.py
- prometheus_client/platform_collector.py
- prometheus_client/process_collector.py
Those files are not executable, nor have any __main__ function.
Signed-off-by: Igor Gnatenko <i.gnatenko.brain@gmail.com>
> Drop unneeded shebangs

- prometheus_client/openmetrics/parser.py
- tests/openmetrics/test_parser.py
Check for new stuff Go added in 1.13, and also
make sure leading 0s are permitted as some users
want to be able to do fixed-size output.
@SuperQ
> Add checks for various other float formats.

- prometheus_client/registry.py
- tests/test_core.py
This allows target labels as needed by push-based systems to be
provided, in a way that doesn't mess up Prometheus's own
top-down pull based approach to SD.
@SuperQ @RichiH @robskillington @sumeer Here's roughly what I'm thinking. Needs unittests etc.
@beorn7 Your input would be appreciated on the pgw front. https://github.com/OpenObservability/OpenMetrics/issues/63 is the general background. Pgw could continue to do this out of band for grouping labels (potentially with the client library using this as a default), or have this as an option.
> Add target_info to registries

- .travis.yml
- setup.py
- tox.ini
Python 3.8 was released recently. This runs tests and adds the classifer to indicate Python 3.8 is supported.
> Add support for Python 3.8

- prometheus_client/parser.py
- tests/test_parser.py
Closes: https://github.com/prometheus/client_python/issues/461
> Add support for parsing timestamps.

- prometheus_client/metrics.py
- tests/test_core.py
> Add __repr__ method to metric objects, make them debug friendly.

- setup.py
To ease the transition to #457:
`python setup.py sdist bdist_wheel`
will produce the universal wheel in addition to the sdist.
> Update setup.py to produce universal wheels

- prometheus_client/metrics.py
- prometheus_client/metrics_core.py
- prometheus_client/openmetrics/parser.py
- prometheus_client/utils.py
- tests/openmetrics/test_exposition.py
- tests/openmetrics/test_parser.py
- tests/test_core.py
- tests/test_exposition.py
Per OM discussions. I also extended this to _gsum,
where as it's a gauge we can allow a negative value
if there's a negative bucket.
@SuperQ
> Allow for negtive histogram buckets.

- prometheus_client/exposition.py
- tests/test_exposition.py
In Python 3.7.6, a patch has been released that changes the behavior of `urllib.parse.urlparse`. This causes an error when pushing to a gateway without a scheme specified in the url string, but with a port. 
Patch details here: https://bugs.python.org/issue27657
Proof of failure on my local branch:
```
client_python gmoss$ python3 --version
Python 3.7.6
client_python gmoss$ git diff
diff --git a/prometheus_client/exposition.py b/prometheus_client/exposition.py
index 4cac223..5c2b8b1 100644
--- a/prometheus_client/exposition.py
+++ b/prometheus_client/exposition.py
@@ -30,7 +30,7 @@ CONTENT_TYPE_LATEST = str('text/plain; version=0.0.4; charset=utf-8')
PYTHON26_OR_OLDER = sys.version_info < (2, 7)
-PYTHON376_OR_NEWER = sys.version_info > (3, 7, 5)
+PYTHON376_OR_NEWER = False  # …
```
> Bugfix urlparse in python >= 3.7.6

- prometheus_client/mmap_dict.py
This size can have a real impact on performance when a lot of files need
to be read.
The performance relies heavily on the file system cache and having the
possibility to adapt _INITIAL_READ_SIZE can help on memory constrained
systems.
> Use mmap.PAGESIZE constant as value for first read

- MANIFEST.in
I'm trying to update the OpenBSD port of this software and add tests in the process.
In the packaging process the regression tests are used in order to make sure that updates
work properly and that an update of a dependency doesn't break a package.
Having the regression tests in the PyPI tarball would make that much easier.
> include tests on pypi distribution

- prometheus_client/values.py
To document the method as semi-supported.
Adresses #509
> values: add a docstring to MultiProcessValue

- README.md
- prometheus_client/__init__.py
- prometheus_client/asgi.py
- prometheus_client/exposition.py
- prometheus_client/twisted/_exposition.py
- tests/test_asgi.py
- tests/test_wsgi.py
- tox.ini
This PR introduces an ASGI counterpart to the current WSGI app.
The ASGI code itself is moved into a seperate module `asgi.py`, which is conditionally included as it is only valid in Python 3 (due to async/await calls).
> Added ASGI application

- prometheus_client/metrics.py
- tests/test_core.py
> Raise exception when setting state in non-observable Enum

- README.md
The current multiprocessing documentation is short, and can lead to some confusion.
This PR addresses the following aspects:
- Setting up `prometheus_multiproc_dir` env. var but still fail to collect metrics, usually due to a wrong setting of the variable (see issues https://github.com/prometheus/client_python/issues/490 &  https://github.com/prometheus/client_python/issues/382).
- Separating _mandatory steps_ (1 and 2) from _optional steps_ (3), depending on the usage of `Gauge`. This is because the `mark_process_dead` function does nothing related to `Count`, `Summary` or `Histogram` metrics, as seen in [its definition](https://github.com/prometheus/client_python/blob/master/prometheus_client/multiprocess.py#L152).
cc @brian-brazil
> Improve multiprocessing documentation

- prometheus_client/metrics.py
- tests/test_core.py
- tests/test_exposition.py
Unit append in the name were being removed when *_total* exists. This moves the clean up before appending the unit. 
Refs https://github.com/prometheus/client_python/issues/542
@brian-brazil Should this "repeated" unit raise an ValueError exception instead since this suffix is already append when dumping on WSGI.
> Cleaning up name before appending unit on name

- prometheus_client/openmetrics/parser.py
- tests/openmetrics/test_parser.py
We now only require a specific set of very common le/quantile
labels to be in a canonical form.
> Update canonical floats per openmetrics latest.

- tests/test_core.py
Fix DeprecationWarning for `inspect.getargspec()` and `assertEquals`.
travis [build](https://travis-ci.org/github/prometheus/client_python/jobs/727362680) warnings.
```
=============================== warnings summary ===============================
tests/test_core.py::TestCounter::test_function_decorator
/home/travis/build/prometheus/client_python/tests/test_core.py:49: DeprecationWarning: inspect.getargspec() is deprecated since Python 3.0, use inspect.signature() or inspect.getfullargspec()
self.assertEqual((["r"], None, None, None), inspect.getargspec(f))
tests/test_core.py::TestGauge::test_inprogress_function_decorator
/home/travis/build/prometheus/client_python/tests/test_core.py:110: DeprecationWarning: inspect.getargspec() is deprecated since Python 3.0, use inspect.signature() or …
```
> Fix python3 deprecation warnings

- README.md
I know metrics should be initialized, but I wasn't able to find how to do it if they have labels in this doc. I eventually found the answer in [Brian's blog](https://www.robustperception.io/existential-issues-with-metrics), which is always an amazing source.
> Add example for initializing metrics with labels

- prometheus_client/metrics_core.py
- prometheus_client/openmetrics/parser.py
- prometheus_client/registry.py
- tests/openmetrics/test_parser.py
- tests/test_core.py
Make sure we're catching all the cases in the client too.
This means you can't have a foo counter and a foo_created gauge.
@SuperQ Per the most recent discussions.
> Catch name clashes in the OM parser.

- prometheus_client/openmetrics/parser.py
- tests/openmetrics/test_exposition.py
- tests/openmetrics/test_parser.py
Also remove some dead code. The untaken branches claimed by coverage are
due to loops that always iterate at least once, or because state
machines only ever have known states.
@robskillington this is mostly testing the parser implementation, but this caught some missing general cases too.
Signed-off-by: Brian Brazil <brian.brazil@robustperception.io>
> Make OM code effectively 100% covered.

- README.md
Change package name in pip install instructions to match pypi with - instead of _
> Fix Package Name typo in pip install instructions

- MAINTAINERS.md
Yesterday at the dev-summit, the Prometheus team has proposed @csmarchbanks as the new maintainer for this repo after @brian-brazil's retirement from the project.
This change will only be merged after an announcement on the prometheus-developers mailing list and is subject to lazy consensus.
Thank you, @brian-brazil, for the incredible amount of work done in this repository and for the project in general.
> Change maintainer from @brian-brazil to @csmarchbanks

- README.md
- prometheus_client/bridge/graphite.py
- tests/test_graphite_bridge.py
Graphite has support for tagged metrics with a syntax very similar to
the non-tagged format.  Update GraphiteBridge to support it.
Graphite's carbon tags format is explained here: https://grafana.com/blog/2018/01/11/graphite-1.1-teaching-an-old-dog-new-tricks
@brian-brazil
> Add tags support to GraphiteBridge

- prometheus_client/exposition.py
- prometheus_client/utils.py
- tests/test_exposition.py
This fixes https://github.com/prometheus/client_python/issues/131 and a significant amount of content is discussed in that issue.
This PR adds a new redirect handler utility class that deliberately forwards an unmodified request to the `Location` header provided by a redirect, while preserving the method, headers and data of the original request. As discussed in comments of the PR, HTTP RFC 2616 requires explicit user approval for redirects in certain situations that may alter the meaning or effect of the request. Given this, the default `HTTPRedirectHandler` in `urllib` does not honor redirects for `PUT` and does not preserve all headers and data.
In the case of Prometheus, many users will have some type of in-house "private" deployment of a Prometheus pushgateway server, and e.g. in a …
> Implement redirect handler option.

- prometheus_client/exposition.py
- tests/test_wsgi.py
By default many browsers will attempt to load a /favicon.ico resource from the server. Currently the default wsgi implementation serves metrics on any path and thus will incorrectly return metrics when being asked for a favicon. This PR fixes this behavior by serving an empty response.
> Add separate handling of the /favicon.ico path in the default wsgi implementation

- prometheus_client/metrics.py
- tests/test_core.py
Hello @brian-brazil, 
I wanted to test metric values in my application unit tests but I didn't figured out how to do it (I probably missed something). That's why I propose to add this simple `reset()` method. Do you think it can be useful? Or is there a better way to test than reseting metrics at the beginning of the test?
And thank you for this very useful lib!
> Add a clear() method to metric objects to remove all labelsets

- README.md
- prometheus_client/multiprocess.py
- prometheus_client/values.py
- tests/test_multiprocess.py
I would like to propose a change to move the `prometheus_multiproc_dir` env variable in upper case to follow the convention of such variable. It feels strange to have to declare it in lower case.
The code adds a deprecation warning to inform the user about the change and transform it to upper case if needed. It also take care of precedence in case both are declared.
> Multiprocess environment variable in upper case

- prometheus_client/multiprocess.py
- tests/test_multiprocess.py
Some users use mark_process_dead without going through any of the
`__init__()` logic which sets the new environment variable.
I chose not to put in the warnings in another place as a user will go
through the deprecation path somewhere already.
Fixes #643
> mark_process_dead respects old env var

- prometheus_client/exposition.py
This is a prospective fix for issue #649 
For POSIX installations, nothing changes. For Windows installations, if python>=3.3 is detected, it will use `os.replace`, else it will do a double operation of `os.remove` followed by `os.rename`, either of which may fail and result in (temporarily or permanently) broken metrics.
This can be refined to catch such errors.
> allow textfile to be overwritten on windows

- README.md
> Guidance to avoid duplicate metrics in multiprocess

- prometheus_client/metrics.py
Fixes #638.
It's of course weird to talk abou negative values of an
"amount". However, for the Gauge, which quite regularly will receive
negative increments, the word "amount" is used, too, so I didn't want
to change it everywhere to "value" or something.
AFAIK the only place where negative values are rejected is indeed the
Counter.
Signed-off-by: beorn7 <beorn@grafana.com>
> Document implications of negative observations

- tox.ini
Attrs 21.1.0 does not work with Python 3.4. The release has been yanked
from pypi, but will still get used sometimes, so specify not to install
21.1.0.
Signed-off-by: Chris Marchbanks <csmarchbanks@gmail.com>
> Do not use attrs 21.1.0

- prometheus_client/metrics.py
Make it clear that labelvalues are for internal use only. Right now it
is easy to assume that they provide a way of creating static labels on a
counter, but that is not the case.
Fixes: #398
> Rename labelvalues to _labelvalues

- prometheus_client/metrics.py
- tests/test_core.py
Always check that a metric is observable before changing its value. Fixes #665.
> Raise the correct exception if the metrics are not observable

- prometheus_client/metrics_core.py
- prometheus_client/registry.py
- tests/test_core.py
> [#674] Made the registry restriction handle newly added metrics.

- prometheus_client/registry.py
- tests/test_core.py
#675 introduces a significant performance regression in restricted registry collecting. This attempts to reduce the regression by re-introducing filter code removed in the previous version.
> [#674, #675] Mitigate performance regression by filtering restricted registry collections

- prometheus_client/exposition.py
- tests/test_exposition.py
Fixes #629
The solution is adapted from this StackOverflow answer: https://stackoverflow.com/a/28950776
@csmarchbanks I decided I'd just make the PR so long and if the solution isn't acceptable it can just be closed 👍
> Fix instance_ip_grouping_key not working on macOS

- prometheus_client/exposition.py
- tests/test_exposition.py
When using the push gateway, URLs may be submitted as host or URL.
When using an URL scheme, in case user submits URL with a trailing slash
(eg: `http://localhost:9091/`), the pushgateway server will reply with a
301 (or 307 depending on the version) redirect that is not handled by
the default handler. Leading to a traceback
Simply remove any trailing slash from the base URL
> Remove trailing slash from pushgateway URLs

- prometheus_client/openmetrics/parser.py
- tests/openmetrics/test_parser.py
> Catch non-integer bucket/count values.

- prometheus_client/context_managers.py
- prometheus_client/metrics.py
- prometheus_client/openmetrics/parser.py
- prometheus_client/parser.py
- prometheus_client/samples.py
- setup.py
This is related to https://github.com/prometheus/client_python/issues/491, it doesn't resolve it, but it could be a step into that direction.
This theoretically should not break python 2.7
> Annotate few functions and methods

- prometheus_client/context_managers.py
- prometheus_client/metrics.py
- tests/test_core.py
This is an attempt to use `time()` as a context manager, but still be able to add labels with values that depend on the result of the timed operation. In our case we'd like to monitor the duration of a number of web requests, but still distinguish/label them by the returned HTTP error code. It didn't seem possible to use the provided `time()` helper in this case, but instead we would have to measure the time ourselves and then use something like `metric.labels(status=status_code).observe(duration)`.
Being able to add the label inside the context manager seemed a bit more convenient:
```python
from prometheus_client import Histogram
from requests import get
teapot = Histogram('teapot', 'A teapot', ['status'])
with teapot.time() as metric:
response = get('https://httpbin.org/status/418') …
```
> Allow to add labels inside a context manager

- prometheus_client/__init__.py
- tox.ini
@csmarchbanks Just a small tweak to improve how prometheus_client behaves with IDEs/editors:
In PyCharm, when ctrl-clicking functions/classes of this library to go to their declaration, it takes me to `prometheus_client/__init__.py` instead of where the function/class was actually defined. This seems to happen because `__init__.py` uses assignments instead of imports to re-export members, so I've changed them all to imports.
> Change to imports to fix go-to-declaration in editors

- prometheus_client/metrics.py
We will cast all labelvalues to be strings so we should not force a user
to cast to a string before passing the label.
> Allow labelvalues and labelkwargs to be Any type

- mypy.ini
- prometheus_client/__init__.py
- prometheus_client/exposition.py
Hi,
`mypy==0.931.0` raises the following errors for `prometheus-client==0.13.0`:
Probably the reason of it are two things:
1. #747, https://github.com/prometheus/client_python/pull/747/files#diff-719659a170701715fc787a12f9ceb16910e3d9a5fbe2c5725f91fac76b29f0f1L10, https://github.com/prometheus/client_python/pull/747/files#diff-719659a170701715fc787a12f9ceb16910e3d9a5fbe2c5725f91fac76b29f0f1L11
2. As I know mypy relies on `__all__` declaration and I have no idea why it worked before.
I hope it is fine to include these two things to `__all__`, because of their wider usage compared to other classes/constants mentioned in #747.
Thanks.
> Add missing functions/classes to __all__

- prometheus_client/metrics.py
Dear maintainer @csmarchbanks,
The release of 0.13.0 yesterday appears to have caused us some type checking errors with Mypy (presumably this is a recent effort to annotate this library with types — thanks!).
I think this particular annotation is incomplete though — our code relies on passing `None` here and the code beneath says the following:
```python
if registry:
registry.register(self)
```
In other words, I think this was intended to be optional.
Thanks!
Signed-off-by: Olivier Wilkinson (reivilibre) <oliverw@matrix.org>
> Declare `registry` on `MetricWrapperBase` as `Optional`

- prometheus_client/samples.py
Timestamps in samples or exemplars can be floats or Timestamp objects.
Signed-off-by: Chris Marchbanks <csmarchbanks@gmail.com>
> Relax type constraints Timestamp

- mypy.ini
- prometheus_client/metrics.py
Hi,
It is a small addition to Histogram/Summary/Gauge typings. 
PS I suppose at the current stage it is fine to set disallow_incomplete_defs to True.
> Add typing to Histogram/Summary/Gauge

- prometheus_client/exposition.py
Reproduce the fix in python3.8 http.server by doing a dns lookup and
using the correct address family
Fixes #567
> wsgi server: allow binding to ipv6 address

- prometheus_client/asgi.py
- prometheus_client/bridge/graphite.py
- prometheus_client/exposition.py
- prometheus_client/gc_collector.py
- prometheus_client/metrics.py
- prometheus_client/metrics_core.py
- prometheus_client/platform_collector.py
- prometheus_client/process_collector.py
- prometheus_client/registry.py
- prometheus_client/samples.py
Fixes: #760 
This should cover most of the public surface area used by others. There is more typing work to be done before we can enable stricter types, but this will be a good next step.
> Add type annotations to everything referenced in __init__.py

- README.md
- prometheus_client/asgi.py
- prometheus_client/exposition.py
- tests/test_asgi.py
- tests/test_wsgi.py
Resolves https://github.com/prometheus/client_python/issues/775
If an `Accept-Encoding:gzip` header is present, will compress the output and set the correct `Content-Encoding` header in the response. Added tests for both the wsgi and asgi implementations.
> Add support for gzip content-encoding

- prometheus_client/metrics.py
- prometheus_client/metrics_core.py
- prometheus_client/samples.py
@csmarchbanks Thanks for maintaining the project! A small patch to improve the readability of type annotations:
int values are acceptable to float variables:
https://www.python.org/dev/peps/pep-0484/#the-numeric-tower
Signed-off-by: Yiyang Zhan <pon.zhan@gmail.com>
> Simplify type annotations for number types

- README.md
- prometheus_client/metrics.py
- tests/test_core.py
Users can disable the automatic creation of _created metrics by
specifying the environment variable PROMETHEUS_DISABLE_CREATED_SERIES.
This is controlled by an environment variable as an end user may not
have control over which registry is being used/when metrics are created.
Alternatively, we could force this to be done on the registry level and filter the metrics out
but that would not help users with custom registries. Happy to hear feedback that another
approach should be taken though.
Closes: #672
> Disable exporting of _created metrics via env var

- prometheus_client/exposition.py
- tests/test_exposition.py
Other libraries depend on this function and we did not mean to create a breaking change. Add a test to document that this is part of the API.
Fixes https://github.com/prometheus/client_python/issues/795
> Rename choose_formatter back to choose_encoder

- README.md
- prometheus_client/metrics.py
- prometheus_client/multiprocess.py
- tests/test_multiprocess.py
Hi!
I work on a multiprocess Flask application and we recently found ourselves wanting the equivalent of the `max` multiprocessing mode, but only for live processes. I came here to poke around the code and also noticed this recent issue asking for a `sum` mode https://github.com/prometheus/client_python/issues/793 , so it seems like there's some interest in more multiprocess modes.
If I understand correctly, the core change needed to support this is actually around the deletion of the files when a process dies - files for `live*` metrics should be deleted, others should not. So I added the new modes with the same collection logic as their non-live counterparts and expanded the check in `mark_process_dead()` to automatically include any metric with `live` as part of its multiprocess mode …
> Add `sum`, `livemin`, and `livemax` multiprocess modes for `Gauge`s

- README.md
The command says pip install prometheus_client (underscore) but the steps above and PyPi says prometheus-client (dash) 
Signed-off-by: Alexa Griffith  <agriffith96@gmail.com>
> updated README installation command

- prometheus_client/exposition.py
- tests/test_exposition.py
The original choose_encoder function was accidentally renamed in 0.14.0 to choose_formatter. In 0.14.1 we left both functions but with choose_formatter marked deprecated and to be removed by 0.15.0.
> Remove choose_formatter before 0.15.0 release

- README.md
I spent a while trying to figure out how to remove these default metrics. Im updating the docs with instructions to remove `process`, `gc`, and `platform` collector metrics. 
Please let me know if my language regarding prometheus is correct, and I will gladly update it
> updated docs with code to remove default metrics

- prometheus_client/mmap_dict.py
Reduce the initial mmap file size from 1MiB to 64KiB. This should reduce the memory and disk overhead for larger numbers of multiprocess workers.
Signed-off-by: SuperQ <superq@gmail.com>
> Reduce the mmap minimum size

- prometheus_client/exposition.py
- prometheus_client/metrics_core.py
- tox.ini
Hello ✋🏻 I decided to fix one problem in the library, but along the way I ran into another problem - flake8 did not work.
<details>
<summary>Traceback here</summary>
```
evgenymarkov@hellroot python-prometheus % python -m tox -e flake8
flake8 recreate: /Users/evgenymarkov/Personal/python-prometheus/.tox/flake8
flake8 installdeps: flake8==3.7.8, flake8-docstrings==1.5.0, flake8-import-order==0.18.1
flake8 installed: entrypoints==0.3,flake8==3.7.8,flake8-docstrings==1.5.0,flake8-import-order==0.18.1,mccabe==0.6.1,pycodestyle==2.5.0,pydocstyle==6.1.1,pyflakes==2.1.1,snowballstemmer==2.2.0
flake8 run-test-pre: PYTHONHASHSEED='1913327212'
flake8 run-test: commands[0] | flake8 prometheus_client/ tests/ setup.py
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
File …
```
> Upgrade development dependencies, fix some types

- prometheus_client/metrics.py
- prometheus_client/mmap_dict.py
- prometheus_client/multiprocess.py
- prometheus_client/values.py
- tests/test_multiprocess.py
Issue #211
Add support for storing the metrics help text in the multiprocess map.
The help will come from the first process read, but it should be the
same for all metrics.
@csmarchbanks not sure if i missed anything but let me know if you need anything changed
> Support metric help text in multiprocess mode

- prometheus_client/parser.py
- tests/openmetrics/test_parser.py
- tests/test_parser.py
If there is no delimiter separating the labels and value when parsing the Prometheus format the parser currently will chop off the first digit of the value. Instead, allow a missing delimiter in the Prometheus format to align with what the Go parser does.
In addition, add a test to specifically check that a delimiter is still required in OpenMetrics.
Fixes: #871
> Allow Prometheus parser to handle missing space

- .circleci/config.yml
- setup.py
- tox.ini
The base image has also been moved to the new cimg repositories which are direct replacements for circleci.
> Add tests for Python 3.11

- prometheus_client/context_managers.py
- prometheus_client/metrics.py
`ExceptionCounter.__exit__` kicks down to `isinstance`, which accepts either a single type or a tuple of types (or in Python 3.10, a UnionType).  Update type annotations to reflect this.
> Allow tuples of exceptions in ExceptionCounter

- prometheus_client/parser.py
@csmarchbanks Hi. Thank you for maintaining the project!
I've added type annotations to the functions in parser.py (issue: #491)
> Add type annotations to parser.py

- prometheus_client/context_managers.py
It would be really nice to be able to use the various decorators without losing the type information of the decorated method.
> Extend type forwarding to other context managers

- MANIFEST.in
the current prometheus wheels include `__pycache__` directories in their package data files.
> avoid installing __pycache__ directories

- README.md
Also provided additional multiprocessing instructions for FastAPI + Gunicorn setup with code examples as per this issue: #810
Signed-off-by: Matas Minelga <minematas@gmail.com>
> Fastapi + Gunicorn example in README

- .circleci/config.yml
- tox.ini
The first failure looks to be an issue with pypy and asgiref typing, pinning asgiref to a specific version fixes it.
The second failure only shows up in py3.7 and py3.8 but involves tox not being able to run if too new of a version of virtualenv is installed. I am not sure exactly what the issue is but at least this keeps CI working for now. The error is:
```
AttributeError: module 'virtualenv.create.via_global_ref.builtin.cpython.mac_os' has no attribute 'CPython3macOsFramework
```
> Fix CI Failures

- prometheus_client/bridge/graphite.py
This was creating python version issues during installation. usr/bin/python points to a different version of python, than used in virtual env. Somehow, due to restrictions, can't change usr/bin/python. So removed this line. This won't cause any problem to other users.
> Removed usr/bin/python from bridge/graphite.py

- .circleci/config.yml
- setup.py
- tox.ini
Python 3.7 is now end of lifed, which allows additional features from the core typings library.
I am going to leave this up for a couple days to see if there are significant objections.
> Remove Support for Python < 3.8

- prometheus_client/context_managers.py
- prometheus_client/decorator.py
- prometheus_client/exposition.py
- prometheus_client/metrics.py
For python +3.8, use Literal for multiprocess_mode param in Gauge
> Gauge typing improvement

- README.md
Expand our exemplar documentation to include information for how to use the appropriate exposition code and mention the feature flag required in Prometheus to ingest exemplars.
Suggested in #932
cc: @mumrah would you be willing to take a look at this and see if it would have helped you?
> Add documentation for how to export exemplars

- prometheus_client/__init__.py
- prometheus_client/bridge/graphite.py
- prometheus_client/openmetrics/exposition.py
- prometheus_client/openmetrics/parser.py
This was creating python version issues during installation. usr/bin/python points to a different version of python, than used in virtual env. Somehow, due to restrictions, can't change usr/bin/python. So changed to #!/usr/bin/env python. Already have a PR merged for this issue.
> Change #!/usr/bin/python to #!/usr/bin/env python

- tests/test_twisted.py
#670
Using readBody with a transport that does not haven an abortConnection method will trigger the deprecation warning.
Can refer to [#twisted-issue-7762](https://github.com/twisted/twisted/issues/7762).
So I use `_read_response_body` method instead of `readBody` method and now everything works fine with the use case.
```shell
python3.9 -m pytest tests/test_twisted.py
```
```
==================================================================== test session starts =====================================================================
platform darwin -- Python 3.9.17, pytest-7.4.0, pluggy-1.2.0
rootdir: /Users/chenyiqiang/WorkSpace/prometheus/client_python
collected 1 item
tests/test_twisted.py . …
```
> Filter `readBody` deprecation notice in tests

- prometheus_client/platform_collector.py
- prometheus_client/process_collector.py
The `registry` parameter can be passed as `None`, but this wasn't reflected in the typing.
> Mark collector parameter as optional in ProcessCollector and PlatformCollector

- README.md
i found this undocumented feature in the code, it's pretty useful to debug an exporter that return thousand of metrics.
i don't know if having this feature undocumented was intentional or  not
(@csmarchbanks)
> add restricted registry documentation

- .circleci/config.yml
- setup.py
- tox.ini
The [second Python 3.12 release candidate](https://discuss.python.org/t/python-3-12-0rc2-final-release-candidate-released/33105?u=hugovk) is out! :rocket:
> ## Call to action
> 
> We strongly encourage maintainers of third-party Python projects to prepare their projects for 3.12 compatibilities during this phase, and where necessary publish Python 3.12 wheels on PyPI to be ready for the final release of 3.12.0.
Python 3.12.0 final is due out in two weeks: [2023-10-02](https://peps.python.org/pep-0693/).
---
Tested locally via tox:
```console
❯ tox -e py312
py312: install_deps> python -I -m pip install attrs coverage pytest
.pkg: install_requires> python -I -m pip install 'setuptools>=40.8.0' wheel
.pkg: _optional_hooks> python /Library/Frameworks/Python.framework/Versions/3.11/lib/python3. …
```
> Add support for Python 3.12

- README.md
- prometheus_client/metrics.py
- prometheus_client/mmap_dict.py
- prometheus_client/multiprocess.py
- prometheus_client/values.py
- tests/test_multiprocess.py
In the multiprocess mode, the process that exposes the metrics needs to aggregate the samples from other processes. Gauge metric allows users to choose the aggregation mode. This implements 'mostrecent' (and 'livemostrecent') mode where the last observed value is exposed.
In order to support this, the file format is expanded to store the timestamps in addition to the values. The stored timestamps are read by the reader process and it's used to find the latest value.
Closes https://github.com/prometheus/client_python/issues/847
Consideration on the atomicity:
Previously, mmap_dict.py had a comment saying "We assume that reading from an 8 byte aligned value is atomic". With this change, the value write becomes a 16 bytes 8-byte aligned write. The code author (draftcode) tried to find a …
> Add mostrecent aggregation to Gauge

- prometheus_client/__init__.py
- prometheus_client/metrics.py
Fixes #933
This takes the approach of globally enabling/disabling _created metrics still. Another option would be to enable/disable `_created` metrics on each registry, but that would be a larger change as we would have to keep persist the registry on each metric (or filter them out which seems more prone to errors/conflicts?). My thought is to start with the global option, but we could add the registry option for more fine use cases if required in the future?
@SuperQ WDYT?
> Allow enabling/disabling _created metrics from code

- prometheus_client/samples.py
- tests/test_samples.py
```
__lt__ is the negation of __gt__ by default.
so samples.Timestamp(1, 1) > samples.Timestamp(1, 1) is false
and samples.Timestamp(1, 1) < samples.Timestamp(1, 1) is true.
but  samples.Timestamp(1, 1) < samples.Timestamp(1, 1) should be false too.
add __lt__ func to fix the bug
```
> fix: error in determining timestamp less than

- docs/content/instrumenting/_index.md
Closes https://github.com/prometheus/client_python/issues/990
> Update documentation for disabling _created metrics

- docs/content/multiprocess/_index.md
- prometheus_client/metrics.py
- tests/test_multiprocess.py
Update documentation and added code warning for remove() and clear() in multi-process mode, its not to close #916 but to provide extra information for users.
> Update documentation and added code warning for remove and clear in multi-process mode

- prometheus_client/openmetrics/exposition.py
OpenMetrics has been released (for a long time now) and we support 1.0.0 not 0.0.1. See https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md#overall-structure for more detail.
> Update OpenMetrics Content Type to 1.0.0

- docs/content/exporting/http/_index.md
- prometheus_client/exposition.py
Hello @csmarchbanks, I made the `start_http_server` function a bit easier to cancel gracefully.
> Enable graceful shutdown for start_{http,wsgi}_server

- prometheus_client/exposition.py
The code introduced to improve binding to an IPv6 address is based on similar code in Python itself, but is missing some critical arguments to the **socket.getaddrinfo()** call: in particular, the socket type must be set to **SOCK_STREAM**, because we want a TCP connection; the **AI_PASSIVE** flag should also be passed because we intend to use the result for binding a listen socket rather than making an outbound connection.
> wsgi server: address family discovery is not quite right

- prometheus_client/metrics.py
- tests/test_core.py
Add a sanity check when set info's label. value can't be null.
@csmarchbanks ptal.
fix #1011
> Add sanity check for label value

- docs/content/exporting/http/_index.md
- prometheus_client/exposition.py
This change addresses issue #1018 (currently, any HTTP method is handled by returning success and metrics data, which causes network scanners to report issues).
Note, this needs careful review w.r.t.:
* Does Prometheus issue any HTTP requests that are now rejected.
* Does HEAD need to be supported.
* Does the `/metrics` resource for which metrics are returned, need to be configurable by the users of this package.
* Does the strict handling need to be enabled/disabled by the users of this package.
* Are unit tests needed.
Note, the pinning of asgiref==3.6.0 removes a test error in the py3.8 tox environment (same fix that already existed for the pypy3.8 tox environment). I don't know why the error on py3.8 comes up in the first place. I guess someone more experienced than me needs to look …
> Reject invalid HTTP methods and resources

- prometheus_client/metrics.py
- prometheus_client/registry.py
- prometheus_client/utils.py
- prometheus_client/values.py
- tests/test_core.py
While using `django-prometheus` I found a situation where adding a metric to the registry caused a read from cache. I had cache metrics enabled, which attempted to add cache metrics to the registry. This resulting in a deadlock as the second registry call attempted to obtain the lock already held lower on the call stack.
I changed usage to an RLock, which allows the lock to be obtained in a nested fashion within a call stack. This still provides thread safety.
> Use re-entrant lock.

- prometheus_client/exposition.py
> Fix `write_to_textfile` leaves back temp files on errors

- prometheus_client/exposition.py
- prometheus_client/metrics.py
- prometheus_client/metrics_core.py
- prometheus_client/openmetrics/exposition.py
- prometheus_client/openmetrics/parser.py
- prometheus_client/parser.py
- prometheus_client/validation.py
- tests/openmetrics/test_exposition.py
- tests/openmetrics/test_parser.py
- tests/test_core.py
- tests/test_exposition.py
- tests/test_parser.py
Adding support for UTF-8 required substantial reworking of the parsing code because the previous code relied on regexes and .index calls that would incorrectly find characters inside quote marks. Note that this means the previous code was already broken for parsing exposition text where characters like braces and hashes were in label values. I have added tests to exercise the edge cases I can think of.
Does not address content negotiation, which will be a followon.
part of https://github.com/prometheus/client_python/issues/1013
> Support UTF-8 in metric creation, parsing, and exposition

- prometheus_client/metrics.py
- prometheus_client/registry.py
- prometheus_client/values.py
- tests/test_core.py
The first commit fixes a correctness bug introduced in
0014e9776350a252930671ed170edee464f9b428 resulting in eg. lost updates during some scenarios.
The code being locked is not reentrant safe. It's preferable to deadlock in these situations instead of silently loosing updates for example or allowing data corruption (mmap_dict).
Consider this example
```python
from prometheus_client import Counter
my_counter = Counter('my_counter', 'my_counter description', labelnames=["bug"])
class Tracked(float):
def __radd__(self, other):
my_counter.labels(bug="isit").inc(1)
my_counter.labels(bug="race").inc(10)
return self + other
def __str__(self):
return f"Tracked({float(self)})"
def main():
my_counter.labels(bug="race").inc(Tracked(100))
for sample in my_counter.collect()[0].samples:
print(sample) …
```
> Fix incorrect use of reentrant locks

- .circleci/config.yml
- setup.py
- tox.ini
Python 3.8 already reached its EOL last month. Remove support and testing of Python 3.8 .
> Remove Python 3.8 support

- prometheus_client/metrics.py
Currently raises an error if labelvalues is not in _metrics. Since the labelvalues get removed anyways, there isn't really any point of this error, since we would want to assume that after running this function call labelvalues will not exist regardless of it existed beforehand or not.
> Check if labelvalues is in _metrics before deletion in MetricWrapperBase.remove()

- docs/content/exporting/pushgateway.md
I tried to make the documentation on the Pushgateway slightly more readable, and added a small note about what the Pushgateway is supposed to do. I'm still quite new to Prometheus, so I hope this will be helpful.
> Changed pushgateway.md

- tests/test_core.py
For a university course, I tested this project for flaky tests, which are tests that can both pass or fail without changes to their code. I noticed that the tests changed in #1070 fail when their execution order is changed because the legacy validation is enabled in some tests but disabled in the test that follows. Since the execution order is not ensured, it's safer to disable them in the same test.
With these changes applied, the whole test suit passes every time even when executed in random order.
> Fix order-dependent flaky tests related to UTF-8 support

- .github/workflows/github-pages.yaml
With the deprecation of artifact@v3 the docs pipeline is no longer working. Upgrade all of the versions while in the file.
> Update versions for docs Github actions

- prometheus_client/exposition.py
Requesting /favicon.ico sends an empty HTTP header:
```
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /favicon.ico HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.88.1
> Accept: */*
>
* HTTP 1.0, assume close after body
< HTTP/1.0 200 OK
< Date: Mon, 07 Apr 2025 14:24:35 GMT
< Server: WSGIServer/0.2 CPython/3.12.9
< :
< Content-Length: 0
<
* Closing connection 0
```
The empty header right before `Content-Length` breaks strict proxies/middleware.
> Don't send an empty HTTP header for /favicon.ico

- pyproject.toml
With the release of [PEP-639](https://peps.python.org/pep-0639/) the best practice for specifying the license is now to use a license expression in the license field and specify any license files in license-files rather than the table-based approach from [PEP-621](https://peps.python.org/pep-0621/#license). Including the license in the classifiers is also no longer allowed when using PEP-639 and has been removed.
> Use License Expressions in pyproject.toml

- prometheus_client/__init__.py
- prometheus_client/exposition.py
- prometheus_client/openmetrics/exposition.py
- prometheus_client/registry.py
- prometheus_client/validation.py
- tests/openmetrics/test_exposition.py
- tests/test_asgi.py
- tests/test_exposition.py
- tests/test_parser.py
- tests/test_twisted.py
- tests/test_wsgi.py
- tools/simple_client.py
Part of https://github.com/prometheus/client_python/issues/1013
The remaining piece is configuration to force escaping even if a scraper does not request it
> UTF-8 Content Negotiation

- prometheus_client/exposition.py
While the `try/except` block does prevent most of the temp files from persisting, if there is a non catchable exception, those temp files continue to pollute the directory. Optionally set the temp directory would let us write to something like `/tmp`, so the target directory isn't polluted. 
This does mean that the target and source filesystems could be different, hence I've used `shutil` here. I didn't want to modify the original behavior, specifically for the Windows bit, so I've kept it as is. `shutil` will use `os.rename` if the filesystems are the same, so we don't lose that atomic behavior in that case.
> Add support to `write_to_textfile` for custom tmpdir

- prometheus_client/asgi.py
- tests/test_asgi.py
The `_bake_output` function in `exposition.py` expects the `params` argument to be a `dict[str, Any]` but the ASGI interface does not handle encoding, thus the parameters are passed in as `dict[bytes, Any]`.
> Fix bug which caused metric publishing to not accept query string parameters in ASGI app

- prometheus_client/exposition.py
- prometheus_client/openmetrics/exposition.py
- prometheus_client/utils.py
Fixes https://github.com/prometheus/client_python/issues/1135
> fix: use tuples instead of packaging Version
