- README.md
- prometheus_client/__init__.py
- tests/test_client.py
@beorn7 
I didn't add linearBuckets/exponentialBuckets as Python has range() and list comprehensions are easy.
> Add histogram support.

- prometheus_client/core.py
- tests/test_client.py
> Add ability to time durations for gauges.

- prometheus_client/exposition.py
Removes registry default value from push_to_gateway and pushadd_to_gateway
References #39 and #40
> Removes registry default value

- prometheus_client/core.py
Adds docstring for Gauge class
> Adds docstring for Gauge method

- prometheus_client/core.py
This comes from changes made by @brian-brazil to __init__.py. This applies those changes to core.py
> Allow for other ways for values to be managed.

- prometheus_client/bridge/graphite.py
This file had varying indentation levels.
There was also an unused local.
> Fixed graphite.py formatting.

- prometheus_client/exposition.py
Issue #51 
Wrapped socket operation inside context manager to makes sure it gets closed.
> Closing open socket in instance_ip_grouping_key()

- prometheus_client/bridge/graphite.py
- prometheus_client/core.py
- prometheus_client/exposition.py
- prometheus_client/parser.py
- prometheus_client/process_collector.py
- tests/test_client.py
- tests/test_exposition.py
- tests/test_parser.py
- tests/test_process_collector.py
@beorn7 Would you mind taking a peek at this to see if I've missed anything major? Main code is in parser.py, the rest is surrounding changes for this to make sense and have the right data structures.
The motivation is that Zalando's Zmon has a partial implementation of the text parser, so I'd like to offer them an official option.
> WIP: Text format parser for Python

- prometheus_client/process_collector.py
- tests/test_process_collector.py
Code:
- remove unused imports
- remove a useless try/except/raise that wraps a os.path.join()
Style:
- max line length 119
- use 4 spaces for indentation
- fix indentation of continuation lines
> Clean up the ProcessCollector.

- prometheus_client/parser.py
- tests/test_parser.py
> For unknown types, suffix should be empty string.

- prometheus_client/exposition.py
> Ensure we return a 500 on collection error.

- prometheus_client/parser.py
- tests/test_parser.py
These are permitted by the format.
> Support trailing commas in parser

- prometheus_client/core.py
@brian-brazil at least from reading, this *looks* wrong, though I haven't run the code, and not sure how to run tests.
> Fix double doubling of mmap file capacity

- prometheus_client/core.py
- tests/test_multiprocess.py
See https://github.com/prometheus/client_python/issues/158 for details.
> Fix namespace and subsystem in multiprocess mode

- prometheus_client/core.py
This cuts ~350ns off the time for an operation, bringing it to
~1700ns.
In multi process mode it's a reasonable assumption that there
isn't any threading going on, so a single lock is faster than
more granular locks.
Fixed #112
> Use only a single global lock for multiproc.

- prometheus_client/bridge/graphite.py
- prometheus_client/core.py
This is a rollback PR of #106 because of buggy timestamp results of timeit.default_timer.
> Should use standart time.time instead of timeit.default_timer

- prometheus_client/process_collector.py
I also ran into the issue described in #95. It's a show stopper for me right now so I made a PR :)
Cheers!
> Fix #95: catch OSError when collecting file descriptors.

- prometheus_client/multiprocess.py
The goal here is to evaluate the environ only at parse time : I tried to mock the variable to make some unittests, but I hit those lines : I cannot patch the environ to fill a temp destination for that test
@brian-brazil any comment on this ?
> multiprocess: pass None as default argument

- prometheus_client/__init__.py
- prometheus_client/core.py
- prometheus_client/multiprocess.py
- prometheus_client/parser.py
- tests/test_exposition.py
- tests/test_multiprocess.py
- tests/test_parser.py
- tox.ini
Fixes lint errors E111 and E114, no semantic changes.
> Make indentation multiple of 4 spaces

- prometheus_client/core.py
Simple optimizations of tuple using.
> Optimizations for tuples using. Removed unused types transformations.

- prometheus_client/core.py
- tox.ini
Resolves W503.
Also drive-by move definition of gauge multiprocess modes.
> Fix lint related to operator positioning

- prometheus_client/parser.py
- tests/test_parser.py
This PR introduces a fix for escape sequence handling bugs introduced in #282.
It uses far less regexes than #289. In theory, one could stop using regexes completely, but that would come with a performance hit.
> Fix unescaping take 2

- prometheus_client/core.py
- prometheus_client/exposition.py
Also fixes a syntax-y error from https://github.com/prometheus/client_python/commit/682e5ecf5c1522bdd7223e49e7e383925a6bbe36
@brian-brazil Pinging as requested :)
> Only open the mmap for reading if read_mode=True

- prometheus_client/exposition.py
Signed-off-by: Brian Brazil <brian.brazil@robustperception.io>
> Fix import of openmetrics, and make accept handling more general.

- prometheus_client/openmetrics/parser.py
- tests/openmetrics/test_parser.py
@SuperQ per the last two meetings.
> Check for negative counter-like and guage histogram values.

- prometheus_client/__init__.py
- prometheus_client/core.py
- prometheus_client/decorator.py
- prometheus_client/exposition.py
- prometheus_client/metrics.py
- prometheus_client/metrics_core.py
- prometheus_client/mmap_dict.py
- prometheus_client/multiprocess.py
- prometheus_client/openmetrics/exposition.py
- prometheus_client/openmetrics/parser.py
- prometheus_client/parser.py
- prometheus_client/process_collector.py
- prometheus_client/registry.py
- prometheus_client/samples.py
- prometheus_client/utils.py
- prometheus_client/values.py
- tests/openmetrics/test_exposition.py
- tests/openmetrics/test_parser.py
- tests/test_core.py
- tests/test_exposition.py
- tests/test_gc_collector.py
- tests/test_graphite_bridge.py
- tests/test_multiprocess.py
- tests/test_parser.py
- tests/test_twisted.py
- tox.ini
Hey @brian-brazil 
Earlier flake8 test were failing. 
I have fixed the tests.
P.S: This is my first PR on this repo. Let me know if I have missed anything. 
Thanks.
> flake8 test passing

- .travis.yml
Travis changed things under the covers, breaking 2.6.
Signed-off-by: Brian Brazil <brian.brazil@robustperception.io>
> Use Trust for 2.6

- setup.py
See: https://packaging.python.org/guides/making-a-pypi-friendly-readme/
https://packaging.python.org/guides/making-a-pypi-friendly-readme/#including-your-readme-in-your-package-s-metadata
> Inject readme.md to long_description so it will show up on the pypi project page.

- prometheus_client/process_collector.py
- tests/test_process_collector.py
> make global _PAGESIZE variable a class member

- prometheus_client/exposition.py
- tests/test_exposition.py
> Handle empty label values for the pushgateway.

- prometheus_client/openmetrics/parser.py
- tests/openmetrics/test_parser.py
As per current spec draft blank lines are not allowed
> openmetrics: Throw error on blank line

- .travis.yml
- prometheus_client/__init__.py
- prometheus_client/core.py
- prometheus_client/exposition.py
- prometheus_client/metrics_core.py
- prometheus_client/mmap_dict.py
- prometheus_client/openmetrics/parser.py
- prometheus_client/parser.py
- prometheus_client/twisted/_exposition.py
- setup.py
- tests/openmetrics/test_parser.py
- tests/test_asgi.py
- tests/test_exposition.py
- tests/test_twisted.py
- tests/test_wsgi.py
- tox.ini
Related [discussion](https://groups.google.com/g/prometheus-developers/c/zOnMpZOOdZ4)
* Add lint stage for: flake8 and isort
* Add E731 to flake8 config in tox.in  `do not assign a lambda expression, use a def`
* Clean up W504(line break after binary operator), unused imports, reorder imports and fix indentation
* Remove deprecated `sudo` keyword from `.travis.yml` and also add `os: linux`
> WIP: Add lint stage to CI

- .travis.yml
- setup.py
- tox.ini
Signed-off-by: yzdann <22779039+yzdann@users.noreply.github.com>
> Add support for python3.9

- README.md
> Readme: Add release/changelog link

- prometheus_client/openmetrics/exposition.py
- tests/openmetrics/test_exposition.py
The parsing code already contains tests for parsing exemplars on counters, just the exposition is affected.
@brian-brazil as a member of OpenMetrics would you be willing to review this?
> Allow counters to emit exemplars via OpenMetrics

- .circleci/config.yml
- mypy.ini
- tests/test_core.py
- tests/test_exposition.py
- tests/test_graphite_bridge.py
- tox.ini
Signed-off-by: Chris Marchbanks <csmarchbanks@gmail.com>
> Add mypy linting to the CI pipeline

- README.md
> fix package name error

- prometheus_client/gc_collector.py
> Fix python_gc_objects_collected metadata typo

- .github/workflows/github-pages.yaml
I created a dummy commit that has been removed from this branch to make sure the deploy worked. You can find it at the appropriate link: https://prometheus.github.io/client_python/
> Fix doc site build

- docs/content/exporting/http/asgi.md
Self explanatory 😄 @csmarchbanks
> Fix a typo in ASGI docs

- .circleci/config.yml
- setup.py
- tox.ini
https://www.python.org/downloads/release/python-3130/
> Add support for Python 3.13

- docs/content/multiprocess/_index.md
https://github.com/prometheus/client_python/issues/504#issuecomment-1358161560
So the next person doesn't have to spend 30 min on this.
> Add note on gauge.set_function not working with multiprocessing
